package com.storyshu.storyshu.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.storyshu.storyshu.database.KTDownload;

import com.storyshu.storyshu.database.KTDownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig kTDownloadDaoConfig;

    private final KTDownloadDao kTDownloadDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        kTDownloadDaoConfig = daoConfigMap.get(KTDownloadDao.class).clone();
        kTDownloadDaoConfig.initIdentityScope(type);

        kTDownloadDao = new KTDownloadDao(kTDownloadDaoConfig, this);

        registerDao(KTDownload.class, kTDownloadDao);
    }
    
    public void clear() {
        kTDownloadDaoConfig.clearIdentityScope();
    }

    public KTDownloadDao getKTDownloadDao() {
        return kTDownloadDao;
    }

}
